name: Check PNR Status

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  check-status:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to commit and push changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check PNR status
        env:
          GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        run: python get_status.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f pnr_status_history.json
          git diff --staged --quiet || git commit -m "Update PNR status - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push
